---
- name: Make sure required packages are installed.
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - git
    - curl
    - tree
    - build-essential
    - kdiff3
    - bzip2
    - unzip
    - xclip
    - zsh
    - zsh-antigen
    - stow
    - autojump
    - tmux
    - tmuxinator

- name: Clone dotfiles
  git:
    repo: https://github.com/lnunno/dotfiles.git
    dest: "~/dotfiles"

- name: Install fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "~/.fzf"
    depth: 1

- name: Install Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim

- name: Install Latex packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - texlive-base
    - unzip
    - texlive-binaries
    - texlive-latex-recommended
    - texlive-latex-extra
    - kile
  when: install_latex_packages
