---
- name: Make sure required packages are installed.
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - zsh
    - stow
    - autojump-zsh
    - tmux
    - tmuxinator

- name: Clone dotfiles
  git:
    repo: https://github.com/lnunno/dotfiles.git
    dest: "~/dotfiles"

- name: Install fzf
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "~/.fzf"
    depth: 1

- name: Download zsh antigen
  get_url:
    url: https://cdn.rawgit.com/zsh-users/antigen/v1.3.2/bin/antigen.zsh
    dest: ~/antigen.sh

- name: Install Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim

